# Generated by Django 4.0.3 on 2022-04-04 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0003_book_author_book_is_bestsellingg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_bestsellingg',
            new_name='is_bestselling',
        ),
    ]
